DROP TABLE IF EXISTS BNEXT_USER;
DROP TABLE IF EXISTS CONTACT;

CREATE TABLE BNEXT_USER (
  BNEXT_USER_ID BIGINT SERIAL PRIMARY KEY NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  LAST_NAME VARCHAR(255) NOT NULL,
  PHONE VARCHAR(15) NOT NULL
);

CREATE TABLE CONTACT (
  PHONE VARCHAR(15) PRIMARY KEY NOT NULL,
  CONTACT_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE BNEXT_USER_CONTACT (
  BNEXT_USER_ID BIGINT,
  PHONE VARCHAR(15),
  CONSTRAINT PK_BNEXT_USER_CONTACT PRIMARY KEY (BNEXT_USER_ID, PHONE),
  CONSTRAINT FK_BNEXT_USER FOREIGN KEY (BNEXT_USER_ID) REFERENCES BNEXT_USER (BNEXT_USER_ID),
  CONSTRAINT FK_CONTACT FOREIGN KEY (PHONE) REFERENCES CONTACT (PHONE)
);